name: gh-pages updates

on:
  push:
    branches:
      - master
      - '10.1'
      - '11.0'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
      with:
        repository: NASA-PDS/nasa-pds.github.io
        ref: master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: deploy util script
      run: |
        pip install pds_github_util
        summaries --token ${{ secrets.GITHUB_TOKEN }} --format rst --path ./docs/source/releases/
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull
        git add .
        echo $(git commit -a -m 'automated gh-pages update from pdsen-corral')
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: NASA-PDS/nasa-pds.github.io
        branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
